---
title: "BYU-Idaho Stat 225: Introduction to Statistics in R"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## An Interactive Textbook

This course is intended to familiarize students with foundational concepts and vocabulary in statistics and introduce basic data wrangling and visualization in R.

Those who diligently work through these materials will be well prepared for their next Statistics or Data Science course.

This book is designed to be a digital workbook.  You can download the notes, practice problems and application activities which can be edited locally on your computer.  Completed assignments will be submitted in Canvas as web-page reports.  


### Download Course Material

To download the folder containing all of the exercises, notes and application activities by following these steps:

  1. Create a class folder where you will save all your work throughout this semester.  This can be on your computer locally or in cloud-based storage such as One-Drive or iCloud.
  2. Click on the link below to download the `.zip` file containing all contents of the course website:

<center>
<a href="https://raw.github.com/byuistats/Math221D_Course/main/Student_Work.zip" class="button-download" download>
  Download Course Files
</a>
</center>

  3. Open the `.zip` file
  4. Save the `Student_Work` folder to your class folder created in step 1.  This can typically be done by right clicking the folder then copying and pasting it into the new location. 

These files will be the basis of your coursework.  

There may be additional files to download throughout the semester.  You can save those to your 


### How to Use This Book

Each unit contains:

  * Preparation readings
  * Practice problems
  * Application Activities
  * Assessments
  
**Getting Started** guides you through getting R and R-Studio set up, introduces the tools we will use for the class, and introduces basic statistical concepts to help get you started.  We learn how to use R-Studio to make lovely reports that can be viewed in a web-browser.  It's a gentle enough introduction to enable even those who have never coded before to start working with R.  

**Descriptive Statistics** introduces tools to help understand data.  We review summary statistics and visualizations for quantitative and categorical data types and learn the basic skills to turn data into information.  

**Data Wrangling and Visualization** takes a step further into dealing with messy data and creating better visualizations.  

**Foundations of Statistical Inference** introduces the key concepts for using sample data to make generalized conclusions about a population. We cover probability, hypothesis testing, confidence intervals and other concepts necessary for making the leap from sample to population.  

**Statistical Tests - Part 1 and 2** cover specific inferential statistics for different data types.  

The **Semester Project** is an opportunity for students to demonstrate the skills acquired during the course.  You will be able to find and import data into R, clean the data, create top notch visualizations, perform appropriate statistical analysis and create a beautiful report.

R Help provides additional resources for learning how to use R.


#### Course Objectives

By the end of this semester, students will confidently be able to:

- Import data and apply basic data wrangling to moderately messy data
- Describe data with numerical and graphical summaries
- Make evidence-based decisions regarding situations with inherent randomness
- Investigate questions through the application of probability distributions
- Perform the appropriate statistical analysis based on specific data being analyzed including hypothesis tests and confidence intervals
- Create web-based reports to communicate the results of statistical analyses to relevant audiences
