---
title: "Hypothesis Test Process"
---


# Hypothesis Testing Process

  1. State $H_0$, $H_a$, and pick $\alpha$  
  2. Calculate the **Test Statistic** (evidence against $H_0$)  
  3. Calculate the **P-Value** (the probability of observing our test statistic or more extreme, if $H_0$ were true)  
  4. Compare P-value to $\alpha$  
  5. Check the test requirements  
  6. Make a conclusion  
  
  
# Hypothesis Test Conclusions  

  1. $\text{P-value} < \alpha$:  
      * **Reject** the null hypothesis, $H_0$, in favor of the alternative  
      * "When $P$ is low, reject $H_0$"  
      * **Sufficient Evidence** to support the alternative  
        i.  Bring back to context of the research question.  For example: I have sufficient evidence to suggest that Stat 225 students are, on average, more agreeable than the general population.  
      * Opportunity for a **Type I Error**, rejecting a true null hypothesis  
      
      
  2. $\text{P-value} \ge \alpha$:  
      * **Fail to Reject** the null hypothesis, $H_0$  
      * **Insufficient Evidence** to support the alternative  
        i.  Bring back to context of the research question.  For example: I have insufficient evidence to suggest that Stat 225 students are, on average, less open than the general population.  
